version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 679252296174.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=679252296174.dkr.ecr.us-east-1.amazonaws.com/marketplace-test
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t marketplace-test .
      - docker tag marketplace-test:latest 679252296174.dkr.ecr.us-east-1.amazonaws.com/marketplace-test:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 679252296174.dkr.ecr.us-east-1.amazonaws.com/marketplace-test:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json      
